### ISSUE TITLE
multiple issues with the project

### ISSUE THREAD

**Issue by pradeepkusingh** [JaXt0r/graphql-serverless-demo#1]
I tried to run the project in AWS and getting a couple of errors. I solved most of them. this is the latest error while loading schema files in the handler.

java.lang.NullPointerException: java.lang.NullPointerException
java.lang.NullPointerException
at org.antlr.v4.runtime.CharStreams.fromString(CharStreams.java:222)
at org.antlr.v4.runtime.CharStreams.fromString(CharStreams.java:212)
at graphql.parser.Parser.parseDocument(Parser.java:28)
at graphql.parser.Parser.parseDocument(Parser.java:21)
at graphql.GraphQL.parse(GraphQL.java:525)
at graphql.GraphQL.parseAndValidate(GraphQL.java:501)
at graphql.GraphQL.lambda$parseValidateAndExecute$3(GraphQL.java:490)
at graphql.execution.preparsed.NoOpPreparsedDocumentProvider.get(NoOpPreparsedDocumentProvider.java:11)
at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:486)
at graphql.GraphQL.executeAsync(GraphQL.java:470)
at graphql.GraphQL.execute(GraphQL.java:401)
at de.mdaehnert.graphql.serverless.Handler.handleRequest(Handler.java:33)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by MenchenFive** [comment]
Did you solve it?

**Comment by pradeepkusingh** [comment]
yes, by upgrading libraries.
